project_id = "hmogswuliehwbmcyzfie"

[functions]
  [functions.ai-travel-planner]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-checkout-session]
    verify_jwt = false
  [functions.extract-trip]
    verify_jwt = false
